name: Deploy
on: push
env:
  projectName: 'mangb'
jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist 
          # path: docs/.vitepress/dist 